<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>162616c9-821d-4aca-8dd4-80bb9c85caeb</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0"/>
        <PackageReference Include="Aspire.Hosting.Kafka" Version="9.3.0" />
        <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.3.0" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CharlotteComedy.Gateway\CharlotteComedy.Gateway.csproj" />
      <ProjectReference Include="..\CharlotteComedy.Query\CharlotteComedy.Query.csproj" />
      <ProjectReference Include="..\CharlotteComedy\CharlotteComedy.csproj" />
    </ItemGroup>

</Project>
